### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by ronaldberndev** [RonaldBernDev/Solar#2]
I migrated old flutter version to new version.
But, My project has many errors.
Plz help me!

**Comment by devil0703** [comment]
Hi.
I am Devil.
I have rich experience in flutter development.
I migrated old flutter version to new version.
I think, your project has gradle errors.
So, if you download new module concern with new flutter version, it will be done.

**Comment by ronaldberndev** [comment]
Thank you, devil.
I fixed error.
Thank you.
