### ISSUE TITLE
I am developing Mobile app.

### ISSUE THREAD

**Issue by ronaldberndev** [RonaldBernDev/Solar#3]
Hello, everyone.
Could you explain about how to build?

**Comment by huapengli0703** [comment]
Hello, Ronald.
What do you want exactly?

**Comment by ronaldberndev** [comment]
Actually, I am rookie for this project.
So, I don't know about flutter and development tools.
How to build?

**Comment by huapengli0703** [comment]
I understand what you mean.
To build flutter, you can use android studio and vs code.
According to my experience, I prefer android studio.
And you can use youtobe movie related to flutter.

**Comment by ronaldberndev** [comment]
Oh, thank you for your kind.
Can you give me your email?

**Comment by huapengli0703** [comment]
Sure, markostrauss0703@gmail.com
