### ISSUE TITLE
How to get badge?

### ISSUE THREAD

**Issue by ronaldberndev** [RonaldBernDev/Solar#4]
How to get badge?

**Comment by huapengli0703** [comment]
Which badge do you want?

**Comment by ronaldberndev** [comment]
I heard about badge in github.

**Comment by huapengli0703** [comment]
Yeah...
You can use this url.
https://github.com/4xmen/Get-Github-Achievements?tab=readme-ov-file

**Comment by ronaldberndev** [comment]
Thank you HuaPeng.
